spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(PRjyS0Jl4g5gui3+eRrUOqLY6u2NmwssxAw1A77dOtpvGdxmUN35U1CW8NmK9bN90T7M1NCvNzPk70TTMzUW9zj0KqQIS6nWUIVBiRwAmEJpEDlWIwuy8ACdNV9HMU1aFs6lwcLF9h4=)
    username: ENC(73mbe6WYpNUcZll5MNSTCw==)
    password: ENC(mq3Ta8p1QUHu5bawedSaGjApAMH0e+/t)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

jwt:
  secret:
    key: ENC(vvNeDy5afcRKYPy6Pdy2uIGfROZ6ZVGaYEBgaBPs4cttxYsNvS8PD5Xv9DNMC8tU/gxMtW2wHf4M7igHTjZBLUazfi8m3OyxWbDjXIyup4HAfvN9YrMmnAVTN1fAMKsC)


  thymeleaf:
    cache: false

cloud:
  aws:
    s3:
      bucket: ENC(MVNfeB0sW8i0nQZv2Jy+eBWczZ1PdGVb)
    credentials:
      access-key: ENC(/7Arz0iQHZf1toVV3pwOQfQRXCePIfnPtF5JQh1jO68=)
      secret-key: ENC(GRUuScJFKz9/v2bc/rFIbS3S0LafnAFjX7Neajd3jdSV7/3m48wRVdK0gfzg71tbvA3ccB9+NYg=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

kakao:
  client:
    id: ENC(DmCqicA7Pa7EFxu5XTVtBxYl3K6fHeM1nSl090T2k+aJXj/JxcAnC1++VMpiz2ZU)
  redirect-uri: http://swapswap.shop/login/kakao/callback